# Generated by Django 2.1.7 on 2019-05-13 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=512)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=2048)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Achievement')),
            ],
        ),
    ]
