# Generated by Django 2.1.7 on 2019-05-14 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_achievement_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='achievement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Achievement'),
        ),
    ]
