# Generated by Django 2.1.7 on 2019-05-20 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_character_achievement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='description',
        ),
    ]
