# Generated by Django 2.1.7 on 2019-05-13 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20190513_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='achievement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Achievement'),
        ),
    ]
